@startuml
class Gyro {
    + {static} StepsPerDegree : double <<get>>
    + RotationValueFlip : bool <<get>> <<set>>
    + Gyro(mode:GyroMode, device:DeviceNumber, flipped:bool)
    + RawValue_Next(newValue:short) : void
    + RawValue_Last() : short
    + RawValues_Buffer() : short[]
    + DegreePerSecond_Last() : double
    + {static} Check_Calibration(sender:object, e:ElapsedEventArgs) : void
    + {static} Request_Calibration() : void
    + Start_Calibration(seconds:int) : void
    + {static} GyroModeInterger() : int
}
Gyro --> "Mode" GyroMode
Gyro --> "CalibrationStatus" CalibrationStatus
Gyro --> "DeviceNumber" DeviceNumber
@enduml
