@startuml
class WiFi {
    + Listening : bool <<get>> <<set>>
    <<const>> CLIENT_PORT : int = 11000
    <<const>> WEBSOCKET_PORT : int = 81
    + WiFi()
    + <<override>> Change_GyroMode(mode:GyroMode) : void
    + <<override>> Disconnect_AllNodes() : void
}
Connection <|-- WiFi
@enduml
