@startuml
abstract class Mapping {
    + <<readonly>> WheelMovement_Threshold : int
    + <<readonly>> ButtonPressing_Threshold : int
    - LastMovement_Timestamp : long
    + Mapping(mode:MappingMode, wheelMovement_Threshold:int, buttonPressing_Threshold:int, wheelRadius:double, chairWidth:double)
    + {static} Change_Mapping(mode:MappingMode, wheelRadius:double, chairWidth:double, wheelMovement_Threshold:int, buttonPressingThreshold:int) : void
    + {abstract} Values_Next(rotations:Rotations) : ControllerInput
    # Is_LeftRotation(rotationLeft:double, rotationRight:double) : bool
    # Are_BothRotationsForeward(rotationLeft:double, rotationRight:double) : bool
    # Is_RotationAgainstEachOther(rotationLeft:double, rotationRight:double) : bool
    # {static} Is_OneRotationUnderThreshold(value_One:double, value_Two:double) : bool
    # {static} Are_BothRotationsUnderThreshold(value_One:double, value_Two:double) : bool
    # Is_RotationForward(value:double) : bool
    - Is_ButtonPressAllowed() : bool
    # SingleWheel(wheelDistance:double, isForwardRotation:bool) : (double, double)
    # DualWheel(wheelDistance:double, isRotationAgainstEachOther:bool) : (double distance, double rotation)
    # DualWheel_Turn(wheelDistance:double) : (double, double)
    # DualWheel_Move(wheelDistance:double) : (double, double)
    # What_ButtonPressed(left:double, right:double) : ControllerInput
    # RatioToDegree(length:double, circumference:double) : double
    # AngularVelocityToControllerInput(v1:double, v2:double, b1:bool, b2:bool, b3:bool, b4:bool) : ControllerInput
    # Get_MovementState(value_One:double, value_Two:double) : MovementState
    # MaxAbsolutRotation(rotationOne:double, rotationTwo:double) : double
    - Reset_LastMovement_Timestamp() : void
    + {static} Get_Mode() : MappingMode
    + {static} Get_ButtonPressingThreshold() : int
    + {static} Get_WheelMovementThreshold() : int
    + {static} Get_Wheelchair() : Wheelchair
}
Mapping o-> "_Mapping" Mapping
Mapping --> "Mode" MappingMode
Mapping --> "Wheelchair" Wheelchair
@enduml
