@startuml
class Terminal <<static>> {
    + {static} Other : string <<get>> <<set>> = ""
    - <<const>> VISIBLE_MESSAGES : int = 5
    + {static} Print(sender:object, e:ElapsedEventArgs) : void
    + {static} InterfaceToString() : string
    + {static} Add_Message(message:string) : void
    + {static} Get_MessageHistory() : List<string>
    - {static} Generate_Table() : string
    - {static} Generate_TableLine(node:Node) : string
    - {static} MessageHistoryToString() : string
    - {static} LegendToString() : string
}
class "ConcurrentBag`1"<T> {
}
Terminal o-> "MessageHistory<Message>" "ConcurrentBag`1"
Terminal o-> "format" Formatting
@enduml
