@startuml Wheelchair-Hub
!include .\\Program.puml
!include .\\Analyse\Benchmark.puml
!include .\\Analyse\Playback.puml
!include .\\Analyse\Record.puml
!include .\\Analyse\Sample.puml
!include .\\Communication\Connection.puml
!include .\\Communication\ESP_Now.puml
!include .\\Communication\WiFi.puml
!include .\\Files\SavedOptions.puml
!include .\\Hardware\Gyro.puml
!include .\\Hardware\Node.puml
!include .\\Mapping\GUI.puml
!include .\\Mapping\Mapping.puml
!include .\\Mapping\MappingChecks.puml
!include .\\Mapping\MovementStateDetection.puml
!include .\\Mapping\RealisticWheelchair.puml
!include .\\Mapping\SimpleWheelchair.puml
!include .\\Mapping\WheelchairWithButtons.puml
!include .\\Terminal\Templates.puml
!include .\\Terminal\Terminal.puml
!include .\\Terminal\Terminal2.puml
!include .\\Util\Controller.puml
!include .\\Util\ControllerInput.puml
!include .\\Util\Enums.puml
!include .\\Util\Loop.puml
!include .\\Util\Plot.puml
!include .\\Util\Structs.puml
!include .\\Util\UserInput.puml
!include .\\Util\Wheelchair.puml
@enduml
