@startuml
class Controller <<static>> {
    - <<const>> CLICK_DELAY : int = 200
    - <<const>> CONTROLLER_MAX : int = 32768
    - {static} client : ViGEmClient?
    - {static} controller : IXbox360Controller?
    + {static} Start() : void
    + {static} Refresh_Controller(sender:object, e:ElapsedEventArgs) : void
    + {static} Click_A() : void
    - {static} ValuesToController(input:ControllerInput) : void
    - {static} Handle_Wheelchair(input:ControllerInput) : void
    - {static} Handle_Mouse(input:ControllerInput) : void
    - {static} Handle_Buttons(input:ControllerInput) : void
    - {static} Click_Delay() : void
    + {static} Reset_Controller() : void
}
@enduml
