@startuml
class Gyro {
    - {static} stepsPerDegree : double
    + {static} StepsPerDegree : double <<get>>
    + RotationValueFlip : bool <<get>> <<set>>
    - BufferPointer : short
    - Offset : short <<get>> <<set>>
    - <<const>> BUFFER_SIZE : short = 100
    - <<const>> CALIBRATION_TIME : int = 3
    + Gyro(mode:GyroMode, device:DeviceNumber, flipped:bool)
    + RawValue_Next(newValue:short) : void
    + RawValue_Last() : short
    + RawValues_Buffer() : short[]
    + DegreePerSecond_Last() : double
    + {static} Check_Calibration(sender:object, e:ElapsedEventArgs) : void
    + {static} Request_Calibration() : void
    + Start_Calibration(seconds:int) : void
    - Stop_Calibration(seconds:int) : void
    - {static} GyroModeToStepsPerDegree(mode:GyroMode) : double
    + {static} GyroModeInterger() : int
}
class "List`1"<T> {
}
Gyro --> "mode" GyroMode
Gyro --> "Mode" GyroMode
Gyro --> "CalibrationStatus" CalibrationStatus
Gyro --> "DeviceNumber" DeviceNumber
Gyro --> "CalibrationValues<int>" "List`1"
@enduml
